---
title: "Josh NFLFastR NN"
output: html_document
date: "2024-12-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(nnet)
library(dplyr)
library(caret)
library(nflfastR)
library(tidyverse)
library(keras)
library(neuralnet)
library(tensorflow)
library(fastDummies)

set.seed(13)
```

Need to take more columns for real model
```{r}
gamers <- load_pbp(2023)
games_filtered <- gamers %>% select(game_id, home_team, away_team, home_score, away_score)

games_filtered$home_win <- ifelse(games_filtered$home_score > games_filtered$away_score, 1, 0)

games_filtered$away_win <- ifelse(games_filtered$home_score < games_filtered$away_score, 1, 0)

games_filtered <- games_filtered %>% mutate_if(is.character, as.factor)
```

```{r}
nrows <- floor(.8 * nrow(games_filtered))
trainindex <- sample(c(1:nrow(games_filtered)), nrows)
training <- games_filtered[trainindex,]
testing <- games_filtered[-trainindex,]
```

```{r, eval =FALSE}
model <- keras_model_sequential() %>%
  layer_lstm(units = 64, input_shape = c(num_time_steps, num_features), return_sequences = TRUE) %>%  # LSTM layer with 64 units
  layer_lstm(units = 32) %>%                        # Another LSTM layer with 32 units
  layer_dense(units = 16, activation = 'relu') %>%   # Dense layer with 16 units and ReLU activation
  layer_dense(units = 1, activation = 'sigmoid')     # Output layer with 1 unit for binary classification

```

Loading the games data, but it doesn't have quantitative metrics like EPA
```{r}
games <- nflreadr::load_schedules(2023)
#games %>% filter(home_team == 'KC') %>%
  #view()
#names(games)
```


```{r}
pbp <- load_pbp(2023)
performances <- pbp %>%
  group_by(game_id) %>%
  slice_tail(n=1)%>%
  select(game_id, total_home_epa, total_home_rush_epa, total_home_pass_epa, total_home_comp_air_epa, total_home_raw_air_epa, total_home_comp_yac_epa, total_home_comp_air_wpa, total_home_comp_yac_wpa, total_home_pass_wpa, total_home_raw_air_wpa, total_home_rush_wpa, total_home_raw_yac_epa, total_home_raw_yac_wpa, total_away_comp_air_epa, total_away_comp_air_wpa, total_away_comp_yac_epa, total_away_comp_yac_wpa, total_away_epa, total_away_pass_epa, total_away_pass_wpa, total_away_raw_air_epa, total_away_raw_air_wpa, total_away_raw_yac_epa, total_away_raw_yac_wpa, total_away_rush_epa, total_away_rush_wpa)

games <- games %>% left_join(performances, by = 'game_id')

games <- games %>%
  select(-old_game_id, -nfl_detail_id, -pfr, -pff, -espn, -ftn, -away_qb_id, -home_qb_id, -away_qb_name, -home_qb_name, -away_coach, -home_coach, -referee, -stadium, -stadium_id, -location) 

games$home_win <- ifelse(games$result > 0, 1,0)

games <- games %>% 
  arrange(home_team)

#view(games)
```

Model stuff, running into problem here where too many of the columns are character, need to figure out how to deal w this, allegedly onehot coding but idrk how to do that

```{r}
features <- games %>% select(-home_win)
labels <- games$home_win
#onehot <- dummy_cols(features, remove_first_dummy = TRUE)
#view(onehot)
```

```{r, eval=FALSE}
features_scaled <- scale(onehot) # maybe dont need
```




Below is all chat
```{r, eval=FALSE}
timestep <- 5 # number of previous games taken into acc

farray <- array(NA, dim = c(nrow(features) - timesteps, timesteps, ncol(features)))

for (i in (timesteps + 1):nrow(features)) {
  farray[i - timesteps, , ] <- as.matrix(features_scaled[(i - timesteps):(i - 1), ])
}

larray <- labels[(timesteps + 1):nrow(labels)]
```

```{r, eval=FALSE}
# Define the LSTM model
model <- keras_model_sequential() %>%
  layer_lstm(units = 64,  # Number of LSTM units (can tune)
            input_shape = c(timesteps, ncol(features)),  # (timesteps, features)
            return_sequences = FALSE) %>%  # Whether to return the full sequence or just the output of the last timestep
  layer_dense(units = 32, activation = 'relu') %>%  # Dense layer
  layer_dense(units = 1, activation = 'sigmoid')  # Binary classification (output between 0 and 1)

# Compile the model
model %>% compile(
  loss = 'binary_crossentropy',  # For binary classification
  optimizer = 'adam',            # Optimizer
  metrics = c('accuracy')        # Metrics to track during training
)

# Summary of the model
summary(model)

```

